---
# installHttpdOpenFirewall.yml
# opens firewall / installs httpd / uses Ansible Jinja2 
# templating to create index.html
- name: install httpd / open http firewall port
  hosts: all
#  remote_user: lnxcfg
#  become: true
#  become_method: sudo
  become_user: root
  vars:
    templateSource: '/var/lib/awx/projects/UnixArena_Project/templates/index.j2'
 
  tasks:
        - name: open http firewall port
          firewalld:
              service: http 
              zone: public
              immediate: yes # this is the firewall-cmd --reload
              permanent: true
              state: enabled
        - name: install httpd
          yum:
            name: httpd
            state: present
         
        - name: httpd template for index.html
          template:
            src: "{{ templateSource }}"
            dest: /var/www/html/index.html
            owner: root
            group: root
            mode: 0644
          notify: restart httpd
  handlers:
        - name: restart httpd
          service:
                name: httpd
                enabled: yes
                state: restarted
